/**
 * @desc Store mutations list
 */

export const ADD_BUDGET = 'ADD_BUDGET'
export const SET_CURRENCY_PAIRS = 'SET_CURRENCY_PAIRS'
export const ADD_TRANSACTION = 'ADD_TRANSACTION'
export const UPDATE_BUDGET = 'UPDATE_BUDGET'
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION'
export const SHOW_ERROR = 'SHOW_ERROR'
export const INIT_BUDGETS = 'INIT_BUDGETS'
export const INIT_TRANSACTIONS = 'INIT_TRANSACTIONS'
export const UPDATE_STATISTIC = 'UPDATE_STATISTIC'
export const UPDATE_BUDGET_TRANSACTION_SUMMS = 'UPDATE_BUDGET_TRANSACTION_SUMMS'
